### ISSUE TITLE
permissions to update apps

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/KratosLegacyApplications#1]
Hi, @playpaolo and I are interested in IncompressibleFluidApp for a project. I'm trying to fix it, but i'm unable to push a new branch to the repo.

@roigcarlo @philbucher could you check the permissions?

**Comment by roigcarlo** [comment]
You should have permissions to make PR now.
You need a review for merge as with the Main repo but there is no enforced CI. 

Please reopen in case permissions are incorrectly set
